  server:
    port: 7777
  # spring - mysql driver config
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url : jdbc:mysql://localhost:3306/menudb
      username : ohgiraffers
      password : ohgiraffers
  
  # ????? mapper.xml ??? IoC ????? ??? ? ?? ?? ?? ??
  mybatis:
    # mappers/*.xml : mapper ???? ??? ???? .xml ? ??? ?? ?? 
    # mapper/**/*.xml : mapper ???? ?? ?? ?? ?????? .xml ? ??? ?? ??
    # mappers ?? ?? ??? ** ? ??? ??? ?????? ????
    mapper-locations: mappers/**/*.xml
