spring :
  servlet:
    multipart:
      # ??? ??? ?? ?? ??
      location: C:\Lecture\10_spring-web-mvc\01_lecture-source\chap06-file-upload-lecture-source
      # ??? ??? ?? ?? ??
      max-file-size: 10MB
      # ?? ? ??? ??? ?? ?? ??
      max-request-size: 10MB
      # ?? ???? 2???? ????? ?? ??? ??? ???? ??? ??
      # ????? ????
      # **? ?? ?? ??? ????? ????.
  mvc:
    static-path-pattern: /static/**
